### ISSUE TITLE
Storj projects bouty?

### ISSUE THREAD

**Issue by adevezin** [Storj/storj-bounty-program#7]
Hello, I am the sole developer of [AllStorj](https://github.com/dri94/AllStorj). Incase you are unfamiliar, it is a dropbox style client for Storj on Android. I just found this github and did not see anything about bounties for storj projects such as mine. I was informed that a bounty would be received for developing the app, however I have not heard anything in awhile.

I understand thing sometimes take time. Just looking for further info :)

(Note: I use two github accounts when submitting to AllStorj, sometimes there is confusion that AllStorj is created by two people, however both this account and @dri94 are by me).

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
